# Generated by Django 3.2.8 on 2022-05-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_accred', models.CharField(choices=[('Институционалдык', 'Институционалдык'), ('Программалык', 'Программалык')], max_length=20, verbose_name='Аккредитация')),
                ('name', models.CharField(max_length=100, verbose_name='Название события')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитации',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Administration/', verbose_name='Фото')),
                ('fullname', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('lesson', models.CharField(max_length=50, verbose_name='Предмет')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('participants', models.CharField(max_length=100, verbose_name='Участники')),
                ('organizer', models.CharField(max_length=50, verbose_name='Организатор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Добавление ссылок на видео')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='Хронология/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Хронология',
                'verbose_name_plural': 'Хронология',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Teachers/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=64, verbose_name='Ф.И.О')),
                ('lesson', models.CharField(max_length=100, verbose_name='Предмет')),
                ('experience', models.CharField(max_length=100, verbose_name='Стаж')),
                ('show_main_page', models.BooleanField(default=False, verbose_name='Показать на главной странице')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=64, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='file/accreditation', verbose_name='Подпункты (ссылка на док)необязательное поле')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.accreditation')),
            ],
        ),
    ]
