# Generated by Django 3.2.8 on 2022-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default=1, upload_to='file/category', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chronology',
            name='pub_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
