# Generated by Django 3.2.8 on 2022-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20220526_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='files',
            field=models.ManyToManyField(to='school.File'),
        ),
    ]
