# Generated by Django 3.2.8 on 2022-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_accreditation_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='files',
            field=models.ManyToManyField(null=True, to='school.File', verbose_name='Файлы'),
        ),
    ]
