# Generated by Django 3.2.9 on 2022-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
